# Generated by Django 5.2.1 on 2025-05-22 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
