# Generated by Django 5.0.3 on 2024-04-10 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="women",
            name="cat",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                to="user.category",
                verbose_name="Категории",
            ),
            preserve_default=False,
        ),
    ]
