# Generated by Django 5.2.1 on 2025-05-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_women_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='secret_answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='secret_question',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
