# Generated by Django 5.2.1 on 2025-05-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile_secret_answer_profile_secret_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='secret_question',
            field=models.CharField(blank=True, choices=[('pet', 'Кличка первого питомца'), ('school', 'Название начальной школы'), ('city', 'Город, где вы родились')], max_length=100),
        ),
    ]
