# Generated by Django 5.2.1 on 2025-06-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_secret_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='secret_answer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='secret_question',
        ),
    ]
