# Generated by Django 5.0.3 on 2024-04-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0003_alter_savingsgoal_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savingsgoal",
            name="current_amount",
            field=models.IntegerField(),
        ),
    ]
