# Generated by Django 5.0.3 on 2024-04-10 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expense", "0004_alter_savingsgoal_current_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="savingsgoal",
            name="current_amount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="savingsgoal",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_savings_goals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
